'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8689
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InventorySample.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _0_c2lAlCKN721_oFYo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_c2lAlCKN721_oFYo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _259244933_6719550251418607_4170930654244499784_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("259244933_6719550251418607_4170930654244499784_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _277105611_3083367841925090_4463837430406016997_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("277105611_3083367841925090_4463837430406016997_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _281354233_1217761045703395_6220257735197044251_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("281354233_1217761045703395_6220257735197044251_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2835657() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2835657", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _283632755_1052049865682766_5229883376038495776_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("283632755_1052049865682766_5229883376038495776_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _283655001_1212774319532576_3484356364088127732_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("283655001_1212774319532576_3484356364088127732_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _284230647_755279132160931_3184538705111345635_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("284230647_755279132160931_3184538705111345635_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _284606739_544000350722859_6466199320314739877_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("284606739_544000350722859_6466199320314739877_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _285131826_429087642141727_2292646649392406770_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("285131826_429087642141727_2292646649392406770_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _285194879_485702423357197_5857795355656341133_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("285194879_485702423357197_5857795355656341133_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _285542725_506663994541582_4938205829804285708_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("285542725_506663994541582_4938205829804285708_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _286439043_396229652543072_5641104355142679605_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("286439043_396229652543072_5641104355142679605_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _286996311_369707855048562_4211644717428734689_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("286996311_369707855048562_4211644717428734689_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _287267697_705814747156017_3981998656581145447_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("287267697_705814747156017_3981998656581145447_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _287323758_526645515918416_5866577058563273420_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("287323758_526645515918416_5866577058563273420_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _287843202_2640841286051382_4737913263824895662_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("287843202_2640841286051382_4737913263824895662_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3d4d12027c61fb128bc2c488fb8ab163() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3d4d12027c61fb128bc2c488fb8ab163", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _610c2cd2e194a9635d9cf328_hero_inventory_valuation_methods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("610c2cd2e194a9635d9cf328_hero-inventory valuation methods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7e8b9_1ligtipzipzgdnalyvntkoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7e8b9-1ligtipzipzgdnalyvntkoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property d5b04cc3dcd8c17702549ebc5f1acf1a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d5b04cc3dcd8c17702549ebc5f1acf1a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homeicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inventory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inventory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inventory_icon_png_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inventory-icon-png-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property istockphoto_1166880542_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-1166880542-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Managing_inventory_intelligently() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Managing-inventory-intelligently", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property person_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("person-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property productsicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productsicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property productsiicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productsiicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
